groups:
- name: Alerts_for_Task
  rules:
  - alert: task_high_cpu_usage_50
    expr: sum(rate(container_cpu_usage_seconds_total{container_label_com_docker_swarm_task_name=~".+"}[1m]))
      BY (container_label_com_docker_swarm_task_name, container_label_com_docker_swarm_node_id)
      * 100 > 50
    for: 1m
    annotations:
      description: '{{ $labels.container_label_com_docker_swarm_task_name }} on ''{{
        $labels.container_label_com_docker_swarm_node_id }}'' CPU usage is at {{ humanize
        $value}}%.'
      summary: CPU alert for Swarm task '{{ $labels.container_label_com_docker_swarm_task_name
        }}' on '{{ $labels.container_label_com_docker_swarm_node_id }}'
  - alert: task_high_memory_usage_1g
    expr: sum(container_memory_rss{container_label_com_docker_swarm_task_name=~".+"})
      BY (container_label_com_docker_swarm_task_name, container_label_com_docker_swarm_node_id) > 2e+09
    for: 1m
    annotations:
      description: '{{ $labels.container_label_com_docker_swarm_task_name }} on ''{{
        $labels.container_label_com_docker_swarm_node_id }}'' memory usage is {{ humanize
        $value}}.'
      summary: Memory alert for Swarm task '{{ $labels.container_label_com_docker_swarm_task_name
        }}' on '{{ $labels.container_label_com_docker_swarm_node_id }}'
    # Alert for any instance that is unreachable for >1 minutes.
  - alert: InstanceDown
    expr: up == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "Instance [{{ $labels.instance }}] down"
      description: "[{{ $labels.instance }}] of job [{{ $labels.job }}] has been down for more than 1 minute."
  - alert: node_DiskSpaceFree10Percent
    expr: node_filesystem_free_percent <= 10
    labels:
      severity: warning
    annotations:
      summary: "Instance [{{ $labels.instance }}] has 10% or less Free disk space"
      description: "[{{ $labels.instance }}] has only {{ $value }}% or less free."
  #Service odoo down
  - alert: Doc_manager_absent
    expr: absent(container_cpu_usage_seconds_total{container_label_com_docker_stack_namespace="doc_manager"})
    for: 5s
    labels:
      severity: page
    annotations:
      summary: "Instance {{$labels.instance}} down"
      description: "Instance= {{$labels.instance}}, Service/Job ={{$labels.job}} is down for more than 5 sec."

    #Service postgres_db down
  - alert: Postgres_DB_absent
    expr: absent(container_cpu_usage_seconds_total{container_label_com_docker_stack_namespace="postgres"})
    for: 5s
    labels:
      severity: page
    annotations:
      summary: "Instance {{$labels.instance}} down"
      description: "Instance= {{$labels.instance}}, Service/Job ={{$labels.job}} is down for more than 5 sec."

    #Service gollum_api down
  - alert: Gollum_API_absent
    expr: absent(container_cpu_usage_seconds_total{container_label_com_docker_stack_namespace="gollum"})
    for: 5s
    labels:
      severity: page
    annotations:
      summary: "Instance {{$labels.instance}} down"
      description: "Instance= {{$labels.instance}}, Service/Job ={{$labels.job}} is down for more than 5 sec."

    #Service gollum_face down
  - alert: Gollum_FACE_absent
    expr: absent(container_cpu_usage_seconds_total{container_label_com_docker_stack_namespace="gollum_face"})
    for: 5s
    labels:
      severity: page
    annotations:
      summary: "Instance {{$labels.instance}} down"
      description: "Instance= {{$labels.instance}}, Service/Job ={{$labels.job}} is down for more than 5 sec."

    #Service mongo_db down
  - alert: Mongo_DB_absent
    expr: absent(container_cpu_usage_seconds_total{container_label_com_docker_stack_namespace="mongo"})
    for: 5s
    labels:
      severity: page
    annotations:
      summary: "Instance {{$labels.instance}} down"
      description: "Instance= {{$labels.instance}}, Service/Job ={{$labels.job}} is down for more than 5 sec."

   #Service pgadmin_cliente down
  - alert: Pgadmin_Client_absent
    expr: absent(container_cpu_usage_seconds_total{container_label_com_docker_stack_namespace="pgadmin"})
    for: 5s
    labels:
      severity: page
    annotations:
      summary: "Instance {{$labels.instance}} down"
      description: "Instance= {{$labels.instance}}, Service/Job ={{$labels.job}} is down for more than 5 sec."

    #Service portainer down
  - alert: Portainer_absent
    expr: absent(container_cpu_usage_seconds_total{container_label_com_docker_stack_namespace="portainer"})
    for: 5s
    labels:
      severity: page
    annotations:
      summary: "Instance {{$labels.instance}} down"
      description: "Instance= {{$labels.instance}}, Service/Job ={{$labels.job}} is down for more than 5 sec."

