stages:
  - deploy

deploy_image:
  tags: 
    - lucual18-swarm-pro-shell-master-01
  stage: deploy
  script:
    - docker stack deploy --compose-file docker-compose.yml portainer

  only:
    - lucual18-swarm-pro
