version: '3.2'

services:
  agent:
    image: portainer/agent
    environment:
      AGENT_CLUSTER_ADDR: tasks.agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os==linux]
    networks:
      - agent_network

  ui:
    image: portainer/portainer-ce:latest
    command: ["-H", "tcp://tasks.agent:9001", "--tlsskipverify"]
    networks:
      - agent_network
      - traefik-swarm
    volumes:
      - portainer_data:/data
    deploy:
      labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`portainer_local.dominio.com`)"
      - "traefik.http.routers.portainer.service=portainer@docker"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
      - "traefik.http.routers.portainer.entrypoints=https"
      - "traefik.docker.network=traefik-swarm"
      - "traefik.http.routers.portainer.tls=true"
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]


networks:
  traefik-swarm:
    external: true
  agent_network:
    driver: overlay
    attachable: true

volumes:
  portainer_data:
    external: true
